Hw3
DmitriyKondaurov/Geekhub-FrontEnd-JS_2018 pull request #5
Opened 2018-11-04 02:41 UTC by DmitriyKondaurov

![screencapture-localhost-3000-geekhub-frontend-js_2018-hw3-index-ru-html-2018-11-04-04_40_28](https://user-images.githubusercontent.com/23703403/47959399-df368180-dfeb-11e8-8b7d-6b65f897b143.png)

2018-11-04 21:01 UTC, yana-tsulya commented
підключи Font Awesome лінкою пліз - https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css
я не змогла добратись до твого коду ((

2018-11-18 21:19 UTC, yana-tsulya commented
https://cdnjs.com/libraries/font-awesome :wink:

2018-11-18 21:22 UTC, spolischook commented
It's impossible to review such big PR. 
Make few small rather then one god PR

2018-11-18 21:25 UTC, spolischook requested changes
Move dependencies to package.json

2018-11-18 22:29 UTC, DmitriyKondaurov commented
> It's impossible to review such big PR.
> Make few small rather then one god PR

I did not understand,  what mistakes exactly I made?

2018-11-22 17:04 UTC, spolischook approved these changes

2018-11-22 17:05 UTC, merged

2018-12-04 21:41 UTC, yana-tsulya commented on HW3/index-ru.html
> +                <span class="logo-caption">Театр</span>
цей текст має бути частиною лого - тобто частиною картинки, назву сайту ти просто ховаєш за лого і не показуєш))

2018-12-04 21:41 UTC, yana-tsulya commented on HW3/index-ru.html
> +            <div class="hero_carousel_event-nav_left" title="Previous">&lsaquo;<span class="hide">Previous</span></div>
гарно зроблено, тільки prev/next краще через button робити))